FROM node:22

WORKDIR /app

# Copier package.json et package-lock.json
COPY package*.json ./
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

# Exposer le port 3000
EXPOSE 3000

# Commande de démarrage
CMD ["npm", "run", "dev"]
