# Étape 1 : Build de l'application
FROM node:22 AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Étape 2 : Serveur léger pour Next.js
FROM node:22
WORKDIR /app
COPY --from=builder /app ./
RUN npm install --omit=dev
CMD ["npm", "run", "start"]
EXPOSE 3000
